arch: ppc64le
language: c
addons:
  apt:
    packages:
      - subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip file g++-8 p7zip-full
script:
  - git clone -b v19.07.3 --depth 1 https://git.openwrt.org/openwrt/openwrt.git 
  - cd openwrt 
  - ./scripts/feeds update -a
  - ./scripts/feeds install -a
  - git clone https://github.com/yazdan/tun2socks-Openwrt
  - cp -rf tun2socks-Openwrt/badvpn package/
  - rm -rf tun2socks-Openwrt/
  - mv ../1.config .config 
#  - make oldconfig
  - sed -i "/^CONFIG_DEFAULT_TARGET_OPTIMIZATION/c\CONFIG_DEFAULT_TARGET_OPTIMIZATION=\"-Os -pipe -mno-branch-likely -mips32r2 -march=24kec -mtune=24kec -mdsp\"" .config
  - make download -j20
  - travis_wait 120 make -j8
  
  - 7z a ../bin.7z bin

deploy:
  provider: releases
  skip_cleanup: true
  api_key: ${KEY}
  file_glob: true
  file: 
    - "openwrt/bin/targets/ramips/mt7620/openwrt-ramips-mt7620-tplink_c2-v1-squashfs-sysupgrade.bin"
    - "bin.7z"
  on:
    tags: true
    all_branches: true
